name: clear_hug
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - accelerate==0.21.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - bib-lookup==0.0.29
      - bidict==0.23.1
      - biosppy==2.2.3
      - bitsandbytes==0.45.5
      - boto3==1.38.20
      - botocore==1.38.20
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.1.1
      - datasets==3.5.1
      - decorator==5.2.1
      - deepspeed==0.16.5
      - deprecate-kwargs==0.1.0
      - deprecated==1.2.18
      - dill==0.4.0
      - easydict==1.13
      - einops==0.6.1
      - einops-exts==0.0.4
      - emd-signal==1.6.4
      - exceptiongroup==1.2.2
      - fastapi==0.115.12
      - feedparser==6.0.11
      - ffmpy==0.5.0
      - filelock==3.18.0
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gradio==4.16.0
      - gradio-client==0.8.1
      - grpcio==1.71.0
      - h11==0.14.0
      - h5py==3.13.0
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.30.2
      - idna==3.10
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - julius==0.2.7
      - kiwisolver==1.4.8
      - latex2mathml==3.77.0
      - lazy-loader==0.4
      - llava==1.2.2.post1
      - llvmlite==0.44.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markdown2==2.5.3
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mne==1.9.0
      - mock==5.2.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - multiprocess==0.70.18
      - narwhals==1.34.1
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numba==0.61.2
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.11.0.86
      - orjson==3.10.16
      - packaging==24.2
      - pandarallel==1.6.5
      - pandas==2.2.3
      - pathos==0.3.4
      - peakutils==1.3.5
      - peft==0.15.1
      - pillow==10.4.0
      - platformdirs==4.3.7
      - pooch==1.8.2
      - pox==0.3.6
      - ppft==1.7.7
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydub==0.25.1
      - pyedflib==0.1.40
      - pyemd==1.0.0
      - pygments==2.19.1
      - pyhealth==1.1.6
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytorch-ranger==0.1.1
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - rdkit==2024.9.6
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rpds-py==0.24.0
      - ruff==0.11.4
      - s3transfer==0.12.0
      - safetensors==0.5.3
      - scikit-learn==1.2.2
      - scipy==1.15.2
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sgmllib3k==1.0.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.7
      - starlette==0.46.1
      - svgwrite==1.4.3
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.6.0
      - timm==0.6.13
      - tokenizers==0.15.1
      - tomlkit==0.12.0
      - torch==2.1.2
      - torch-ecg==0.0.31
      - torch-optimizer==0.3.0
      - torchsummary==1.5.1
      - torchvision==0.16.2
      - tqdm==4.67.1
      - transformers==4.37.2
      - triton==2.1.0
      - typer==0.15.2
      - typing-extensions==4.13.1
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - umap-learn==0.5.7
      - urllib3==1.26.15
      - uvicorn==0.34.0
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - websockets==11.0.3
      - werkzeug==3.1.3
      - wfdb==4.3.0
      - wrapt==1.17.2
      - xmltodict==0.14.2
      - xxhash==3.5.0
      - yarl==1.19.0
